get:
  tags:
    - product
  summary: Sort products by category and company.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - $ref: './parameters/category/query-category-id.yaml'
    - $ref: './parameters/company/query-company-id.yaml'
  responses:
    200:
      description: Product sorted.
      content:
        application/json:
          schema:
            $ref: './schemas/product/products.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    404:
      $ref: '../../../../responses/product/product-not-found.yaml'