get:
  tags:
    - auth-audit
  summary: Get user auth audits.
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  parameters:
    - $ref: './parameters/user/query-user-id.yaml'
  responses:
    200:
      description: All audits.
      content:
        application/json:
          schema:
            $ref: './schemas/auth-audit/auth-audits.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    404:
      description: Audits not found.