post:
  summary: Create a new user status.
  tags:
    - user-status
    - admin
  security:
    - cookie-auth: []
    - admin-role: []
  requestBody:
    description: New user status.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            userStatusName:
              type: string
  responses:
    201:
      description: Created new user status.
      content:
        application/json:
          example:
            id: 1
            name: online
            createDate: 00.11.2222
    400:
      $ref: "./responses/400.yaml"
    401:
      $ref: "./responses/401.yaml"
    403:
      $ref: "./responses/403.yaml"
    409:
      $ref: "./responses/409.yaml"

get:
  tags:
    - user-status
    - customer
  summary: Get all user status.
  security:
    - cookie-auth: []
    - admin-role: []
  parameters:
    - $ref: "./parameters/pagination/page-from.yaml"
    - $ref: "./parameters/pagination/page-to.yaml"
  responses:
    200:
      description: All user status received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: "./schemas/user-status.yaml"
    401:
      $ref: "./responses/401.yaml"
    403:
      $ref: "./responses/403.yaml"
    404:
      $ref: "./responses/404.yaml"
