post:
  summary: Create a new user status.
  tags:
    - user-status
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  requestBody:
    description: User status name.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
  responses:
    201:
      description: Created new user status.
      content:
        application/json:
          example:
            id: 1
            name: online
            createDate: 00.11.2222
    400:
      $ref: '../../responses/validation/400.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    409:
      $ref: '../../responses/user-status/user-status-with-this-name-already-exists.yaml'

get:
  tags:
    - user-status
  summary: Get all user status.
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  responses:
    200:
      description: All user status received.
      content:
        application/json:
          schema:
            $ref: './schemas/user-status/user-statuses.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    404:
      description: No user status found.