version: '3.9'

services:
  builder-materials-market-api:
    container_name: ${DOCKER_APP_CONTAINER_NAME}
    networks:
      - bmm_networkd
      - bmm_main_network
    restart: always
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${SERVER_PORT}:8080'
    env_file:
      - .env.docker
    depends_on:
      builder-materials-market-oracle:
        condition: service_healthy
        restart: true

  builder-materials-market-oracle:
    image: 'container-registry.oracle.com/database/enterprise:latest'
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    restart: always
    networks:
      - bmm_networkd
    env_file:
      - .env.docker
    environment:
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_EDITION: ${ORACLE_EDITION}
    ports:
      - '${ORACLE_PORT}:1521'
    volumes:
      - ./data:/opt/oracle/oracle-data
      - ./migrations:/opt/oracle/scripts/startup
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  data:

networks:
  bmm_main_network:
    external: true
  bmm_networkd: