version: '3.9'

services:
  builder-materials-market-oracle:
    image: 'container-registry.oracle.com/database/enterprise:latest'
    container_name: ${DOCKER_DB_CONTAINER_NAME}
    restart: always
    env_file:
      - .env
    environment:
      ORACLE_SID: ${ORACLE_SID}
      ORACLE_PWD: ${ORACLE_PWD}
      ORACLE_PDB: ${ORACLE_PDB}
      ORACLE_EDITION: ${ORACLE_EDITION}
    ports:
      - '${ORACLE_PORT}:1521'
    volumes:
      - ./data:/opt/oracle/oracle-data
      - ./migrations:/opt/oracle/scripts/startup
    ulimits:
      nofile:
        soft: 65536
        hard: 65536

volumes:
  data:
