post:
  summary: Create a new product.
  tags:
    - product
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  requestBody:
    description: Product data.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            companyId:
              type: integer
            categoryId:
              type: integer
            quantity:
              type: integer
              default: 0
            price:
              type: integer
            rating:
              type: integer
              default: 5
            linkToImages:
              type: array
              items:
                type: string
            title:
              type: string
            description:
              type: string
              minLength: 50
  responses:
    201:
      description: Created new product.
      content:
        application/json:
          example:
            companyId: 1
            categoryId: 1
            quantity: 17
            price: 3500
            rating: 4
            linkToImages: [ link, link ]
            title: concrete
            description: concrete
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    404:
      $ref: './responses/404.yaml'

get:
  tags:
    - product
  summary: Get all products.
  responses:
    200:
      description: All product received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/product.yaml'
    404:
      $ref: './responses/404.yaml'