post:
  summary: Create new user delivery.
  tags:
    - delivery
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  requestBody:
    description: Delivery details.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            orderId:
              type: integer
            amount:
              type: number
            addressFrom:
              type: string
            addressTo:
              type: string
            approximateDate:
              type: string
            createDate:
              type: string
  responses:
    200:
      description: Delivery created.
      content:
        application/json:
          schema:
            $ref: './schemas/delivery.yaml'
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'