post:
  summary: Create a new authentication event.
  tags:
    - auth-audit-event
    - admin
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  requestBody:
    description: New audit event name.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            authEventName:
              type: string
  responses:
    201:
      description: Created new auth audit event.
      content:
        application/json:
          example:
            id: 1
            name: successfully logging
            createDate: 00.11.2222
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    409:
      $ref: './responses/409.yaml'

get:
  tags:
    - auth-audit-event
    - admin
  summary: Get all a auth audit events.
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  parameters:
    - $ref: './parameters/pagination/page-from.yaml'
    - $ref: './parameters/pagination/page-to.yaml'
  responses:
    200:
      description: All audit events received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/auth-audit-event.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    404:
      $ref: './responses/404.yaml'