post:
  summary: Create a new order status.
  tags:
    - order-status
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  requestBody:
    description: Name and code for order status.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            code:
              type: integer
              minLength: 3
              maxLength: 3
            name:
              type: string
  responses:
    201:
      description: Created new order status.
      content:
        application/json:
          example:
            id: 1
            code: 402
            name: paid
            createDate: 00.11.2222
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    404:
      $ref: './responses/409.yaml'

get:
  tags:
    - order-status
  summary: Get all order statuses.
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  parameters:
    - $ref: './parameters/limit.yaml'
  responses:
    200:
      description: All order-status received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/order-status.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    404:
      $ref: './responses/404.yaml'