get:
  tags:
    - session
  summary: Get all user sessions.
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  parameters:
    - $ref: './parameters/user/query-user-id.yaml'
  responses:
    200:
      description: All sessions received.
      content:
        application/json:
          schema:
            $ref: './schemas/session/sessions.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    404:
      description: No user sessions found.