ALTER SESSION SET CONTAINER={PBD};

ALTER SESSION SET CURRENT_SCHEMA={USER};

CREATE TABLE "user_role" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"name" VARCHAR(255) NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP
);

CREATE TABLE "user_status" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"name" VARCHAR(255) NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP
);

CREATE TABLE "user" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"user_role_id" INTEGER NOT NULL,
	"user_status_id" INTEGER NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"email" VARCHAR(50) NOT NULL,
	"phone_number" VARCHAR(25) NOT NULL,
	"password_hash" VARCHAR(255) NOT NULL,
	"is_deleted" INTEGER DEFAULT 0,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT ur_u_fk FOREIGN KEY ( "user_role_id" ) REFERENCES "user_role" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT us_u_fk FOREIGN KEY ( "user_status_id" )
	REFERENCES "user_status" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "session" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"user_id" INTEGER NOT NULL,
	"token" VARCHAR(255) NOT NULL,
	"live_time" TIMESTAMP NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT u_s_fk FOREIGN KEY ( "user_id" ) REFERENCES "user" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "auth_audit_event" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP
);

CREATE TABLE "auth_audit" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"user_id" INTEGER NOT NULL,
	"auth_audit_event_id" INTEGER NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT u_aa_fk FOREIGN KEY ( "user_id" ) REFERENCES "user" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT aae_aa_fk FOREIGN KEY ( "auth_audit_event_id" )
	REFERENCES "auth_audit_event" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "order_payment_type" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP
);

CREATE TABLE "order_status" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"code" INTEGER NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP
);

CREATE TABLE "order" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"user_id" INTEGER NOT NULL,
	"order_status_id" INTEGER NOT NULL,
	"order_payment_type_id" NOT NULL,
	"order_number" INTEGER NOT NULL,
	"is_canceled" INTEGER DEFAULT 0,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT u_o_fk FOREIGN KEY ( "user_id" ) REFERENCES "user" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT os_o_fk FOREIGN KEY ( "order_status_id" )
	REFERENCES "order_status" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT opt_o_fk FOREIGN KEY ( "order_payment_type_id" )
	REFERENCES "order_payment_type" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "delivery" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"order_id" INTEGER NOT NULL,
	"ammount" decimal NOT NULL,
	"address_from" VARCHAR(255) NOT NULL,
	"address_to" VARCHAR(255) NOT NULL,
	"approximate_date" TIMESTAMP NOT NULL,
	"is_deleted" INTEGER DEFAULT 0,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT o_d_fk FOREIGN KEY ( "order_id" ) REFERENCES "order" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "order_history" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"order_status_id" INTEGER NOT NULL,
	"order_id" INTEGER NOT NULL,
	"total_quantity" INTEGER NOT NULL,
	"total_cost" decimal NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT os_oh_fk FOREIGN KEY ( "order_status_id" )
	REFERENCES "order_status" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT o_oh_fk FOREIGN KEY ( "order_id" ) REFERENCES "order" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "company" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL,
	"link_to_website" VARCHAR(255) NOT NULL,
	"link_to_logo_image" VARCHAR(255) NOT NULL,
	"phone_number" VARCHAR(25) NOT NULL,
	"email" VARCHAR(50) NOT NULL,
	"description"VARCHAR2(1000) NOT NULL,
	"is_deleted" INTEGER DEFAULT 0,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP
);

CREATE TABLE "category_type" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"name" VARCHAR(50) NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP
);

CREATE TABLE "category" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"category_type_id" INTEGER NOT NULL,
	"name" VARCHAR(50) NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT c_t_id FOREIGN KEY ( "category_type_id" )
	REFERENCES "category_type" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "product" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"company_id" INTEGER NOT NULL,
	"category_id" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	"price" decimal NOT NULL,
	"rating" decimal DEFAULT 5,
	"link_to_images" VARCHAR(255) NOT NULL,
	"title" VARCHAR(50) NOT NULL,
	"description"VARCHAR2(1000) NOT NULL,
	"is_deleted" INTEGER DEFAULT 0,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT cp_p_fk FOREIGN KEY ( "company_id" )
	REFERENCES "company" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT ct_p_fk FOREIGN KEY ( "category_id" )
	REFERENCES "category" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "feedback" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"user_id" INTEGER NOT NULL,
	"product_id" INTEGER NOT NULL,
	"company_id" INTEGER NOT NULL,
	"rating" decimal DEFAULT 5,
	"title" VARCHAR(125) NOT NULL,
	"message" VARCHAR2(1000) NOT NULL,
	"is_deleted" INTEGER DEFAULT 0,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT u_f_fk FOREIGN KEY ( "user_id" ) REFERENCES "user" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT p_f_fk FOREIGN KEY ( "product_id" ) REFERENCES "product" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT c_f_fk FOREIGN KEY ( "company_id" ) REFERENCES "company" ( "id" ) ON DELETE CASCADE
);

CREATE TABLE "order_detail" (
	"id" INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1) PRIMARY KEY,
	"order_id" INTEGER NOT NULL,
	"product_id" INTEGER NOT NULL,
	"is_deleted" number(1) DEFAULT 0,
	"position_number" INTEGER NOT NULL,
	"quantity" INTEGER NOT NULL,
	"create_date" TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	"update_date" TIMESTAMP,
	CONSTRAINT o_od_fk FOREIGN KEY ( "order_id" ) REFERENCES "order" ( "id" ) ON DELETE CASCADE,
	CONSTRAINT p_od_fk FOREIGN KEY ( "product_id" ) REFERENCES "product" ( "id" ) ON DELETE CASCADE
);