post:
  summary: Create new user order delivery.
  tags:
    - delivery
    - customer
  security:
    - cookie-auth: []
    - customer-role: []
  requestBody:
    description: Delivery details.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            orderId:
              type: integer
            addressFrom:
              type: string
            approximateDate:
              type: string
            amount:
              type: integer
            addressTo:
              type: string
  responses:
    200:
      description: Delivery created.
      content:
        application/json:
          schema:
            $ref: "./schemas/delivery.yaml"
    400:
      $ref: "./responses/400.yaml"
    401:
      $ref: "./responses/401.yaml"

get:
  tags:
    - delivery
    - customer
  summary: Get user order delivery.
  security:
    - cookie-auth: []
    - customer-role: []
  parameters:
    - $ref: "./parameters/order/queryOrderId.yaml"
  responses:
    200:
      description: User order delivery received.
      content:
        application/json:
          schema:
            $ref: "./schemas/delivery.yaml"
    401:
      $ref: "./responses/401.yaml"
    404:
      $ref: "./responses/404.yaml"

patch:
  tags:
    - delivery
    - customer
  summary: Set user order delivery.
  security:
    - cookie-auth: []
    - customer-role: []
  parameters:
    - $ref: "./parameters/order/queryOrderId.yaml"
  requestBody:
    description: New user order status
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            addressFrom:
              type: string
            addressTo:
              type: string
            approximateDate:
              type: string
            amount:
              type: integer
  responses:
    200:
      description: User order delivery received.
      content:
        application/json:
          schema:
            $ref: "./schemas/delivery.yaml"
    401:
      $ref: "./responses/401.yaml"
    404:
      $ref: "./responses/404.yaml"

delete:
  tags:
    - delivery
    - customer
  summary: Cancel user order delivery.
  security:
    - cookie-auth: []
    - customer-role: []
  parameters:
    - $ref: "./parameters/order/queryOrderId.yaml"
  responses:
    200:
      description: User order delivery canceled.
      content:
        application/json:
          schema:
            $ref: "./schemas/delivery.yaml"
    401:
      $ref: "./responses/401.yaml"
    404:
      $ref: "./responses/404.yaml"
