post:
  tags:
    - order-history
  summary: Create a new order screenshot.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  requestBody:
    description: Feedback data for creating new feedback.
    required: true
    content:
      application/json:
        schema:
          orderId:
            type: integer
          orderStatusId:
            type: integer
  responses:
    200:
      description: Created new order history screenshot.
      content:
        application/json:
          schema:
            $ref: './schemas/order-history.yaml'
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'