post:
  tags:
    - order-detail
  summary: Add new item to order.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - $ref: './parameters/order/query-order-id.yaml'
    - $ref: './parameters/product/query-product-id.yaml'
  responses:
    200:
      description: Created new order detail.
      content:
        application/json:
          schema:
            $ref: './schemas/order-detail.yaml'
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'