post:
  tags:
    - order-detail
  summary: Add new item to order.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  requestBody:
    description: Feedback data for creating new feedback.
    required: true
    content:
      application/json:
        schema:
          orderId:
            type: integer
          productId:
            type: integer
  responses:
    200:
      description: Created new order detail.
      content:
        application/json:
          schema:
            $ref: './schemas/order-detail.yaml'
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'