post:
  summary: Create a new user role.
  tags:
    - user-role
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  parameters:
    - name: user-role-name
      in: query
      description: New user role name.
      schema:
        type: string
  responses:
    201:
      description: Created new user role.
      content:
        application/json:
          example:
            id: 1
            name: admin
            createDate: 00.11.2222
    400:
      $ref: '../../responses/validation/400.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    409:
      $ref: '../../responses/user-role/user-role-with-this-name-already-exists.yaml'

get:
  tags:
    - user-role
  summary: Get all user roles.
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  responses:
    200:
      description: All user role received.
      content:
        application/json:
          schema:
            $ref: './schemas/user-role/user-roles.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    404:
      description: No user role found.