post:
  summary: Create a new user role.
  tags:
    - user-role
    - admin
  security:
    - cookie-auth: []
    - admin-role: []
  requestBody:
    description: New user role.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            userRoleName:
              type: string
  responses:
    201:
      description: Created new user role.
      content:
        application/json:
          example:
            id: 1
            name: admin
            createDate: 00.11.2222
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    409:
      $ref: './responses/409.yaml'

get:
  tags:
    - user-role
    - admin
  summary: Get all user roles.
  security:
    - cookie-auth: []
    - admin-role: []
  parameters:
    - $ref: './parameters/pagination/page-from.yaml'
    - $ref: './parameters/pagination/page-to.yaml'
  responses:
    200:
      description: All user role received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/user-role.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    404:
      $ref: './responses/404.yaml'
