get:
  tags:
    - feedback
  summary: Sort feedback by rating.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - name: to
      in: query
      description: From maximum to minimum and vice versa.
      required: true
      schema:
        type: string
  responses:
    200:
      description: Feedback sorted.
      content:
        application/json:
          schema:
            $ref: './schemas/feedback/feedbacks.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    404:
      description: Feedbacks not found.