post:
  summary: Create a new category.
  tags:
    - category
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  parameters:
    - name: category-name
      in: query
      description: Category name.
      schema:
        type: string
  responses:
    201:
      description: Created new category.
      content:
        application/json:
          example:
            id: 1
            name: concrete
            createDate: 00.11.2222
    400:
      $ref: './responses/validation/400.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    409:
      $ref: '../../responses/category/category-with-this-name-already-exists.yaml'

get:
  tags:
    - category
  summary: Get all categories.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  responses:
    200:
      description: All categories received.
      content:
        application/json:
          schema:
            $ref: '../../schemas/category/categories.yaml '
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    404:
      description: No categories found.