post:
  summary: Create a new category.
  tags:
    - category
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  requestBody:
    description: New category name.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            categoryName:
              type: string
  responses:
    201:
      description: The new category has been successfully created.
      content:
        application/json:
          example:
            id: 1
            name: concrete
            createDate: 00.11.2222
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    409:
      $ref: './responses/409.yaml'

get:
  tags:
    - category
  summary: Get all categories.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - $ref: './parameters/limit.yaml'
  responses:
    200:
      description: All categories received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/category.yaml'
    401:
      $ref: './responses/401.yaml'
    404:
      $ref: './responses/404.yaml'