post:
  summary: Create a new user order.
  tags:
    - order
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - $ref: './parameters/user/query-user-id.yaml'
    - $ref: './parameters/order-status/query-order-status-id.yaml'
    - $ref: './parameters/order-payment-type/query-order-payment-type-id.yaml'
  responses:
    201:
      description: Created new order.
      content:
        application/json:
          example:
            id: 1
            orderNumber: 9999
            createDate: 00.11.2222
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'