post:
  summary: Create a new user order.
  tags:
    - order
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  requestBody:
    description: Feedback data for creating new feedback.
    required: true
    content:
      application/json:
        schema:
          userId:
            type: integer
          orderStatusId:
            type: integer
          orderPaymentTypeId:
            type: integer
  responses:
    201:
      description: Created new order.
      content:
        application/json:
          example:
            id: 1
            userId: 1
            orderStatusId: 1
            orderPaymentTypeId: 1
            orderNumber: 9999
            createDate: 00.11.2222
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'