get:
  tags:
    - order
    - customer
  summary: Get user order payment type.
  security:
    - cookie-auth: []
    - customer-role: []
  parameters:
    - $ref: './parameters/user/userId.yaml'
    - $ref: './parameters/order/orderId.yaml'
  responses:
    200:
      description: User order payment type received.
      content:
        application/json:
          schema:
            $ref: './schemas/order-payment-type.yaml'
    401:
      $ref: './responses/401.yaml'
    404:
      $ref: './responses/404.yaml'

patch:
  tags:
    - order
    - customer
  summary: Set user order payment type.
  security:
    - cookie-auth: []
    - customer-role: []
  parameters:
    - $ref: './parameters/user/userId.yaml'
    - $ref: './parameters/order/orderId.yaml'
  requestBody:
    description: New user order payment type.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            orderPaymentTypeId:
              type: integer
  responses:
    200:
      description: User order payment type successfully updated.
      content:
        application/json:
          schema:
            $ref: './schemas/order.yaml'
    401:
      $ref: './responses/401.yaml'
    404:
      $ref: './responses/404.yaml'
