get:
  tags:
    - user
  summary: Get all users.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - name: limit
      in: query
      description: Number of users received (not required).
      required: false
      schema:
        type: integer
        default: 15
        nullable: true
  responses:
    200:
      description: All user received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/user.yaml'
    404:
      $ref: './responses/404.yaml'