get:
  tags:
    - user
  summary: Get all users.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - $ref: './parameters/limit.yaml'
  responses:
    200:
      description: All user received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/user.yaml'
    404:
      $ref: './responses/404.yaml'