post:
  summary: Create new company.
  tags:
    - company
    - admin
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  requestBody:
    description: Company information.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            name:
              type: string
            linkToWebSite:
              type: string
            linkToLogoImage:
              type: string
            phoneNumber:
              type: string
              minLength: 10
              maxLength: 15
            email:
              type: string
              minLength: 6
            description:
              type: string
              minLength: 50
  responses:
    201:
      description: Created new company.
      content:
        application/json:
          example:
            id: 1
            name: facebook
            linkToWebSite: https://facebook.com
            linkToLogoImage: /user/admin/server/facebook/images/logo.png
            phoneNumber: 89997776655
            email: facebook@meta.com
            description: many text
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    409:
      $ref: './responses/409.yaml'
get:
  tags:
    - company
    - no-auth
  summary: Get all companies.
  parameters:
    - $ref: './parameters/pagination/page-from.yaml'
    - $ref: './parameters/pagination/page-to.yaml'
    - name: company-title
      in: query
      description: Company tile.
      required: false
      schema:
        type: string
  responses:
    200:
      description: All company received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/company.yaml'
    404:
      $ref: './responses/404.yaml'
