get:
  tags:
    - order
    - customer
  summary: Get all user orders.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - $ref: './parameters/user/userId.yaml'
    - $ref: './parameters/pagination/page-from.yaml'
    - $ref: './parameters/pagination/page-to.yaml'
  responses:
    200:
      description: All orders received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/order.yaml'
    401:
      $ref: './responses/401.yaml'
    404:
      $ref: './responses/404.yaml'
