post:
  tags:
    - order-detail
    - customer
  summary: Add new item to user order.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - $ref: './parameters/order/orderId.yaml'
  requestBody:
    description: New product.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            productId:
              type: integer
            quantity:
              type: integer
              default: 1
  responses:
    200:
      description: Created new user order product.
      content:
        application/json:
          schema:
            $ref: './schemas/order-detail.yaml'
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    404:
      $ref: './responses/404.yaml'

get:
  tags:
    - order-detail
    - customer
  summary: Get all user order products.
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  parameters:
    - $ref: './parameters/order/orderId.yaml'
    - $ref: './parameters/pagination/page-from.yaml'
    - $ref: './parameters/pagination/page-to.yaml'
  responses:
    200:
      description: All products received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/order-detail.yaml'
    401:
      $ref: './responses/401.yaml'
    404:
      $ref: './responses/404.yaml'
