post:
  summary: Create a new order payment type.
  tags:
    - order-payment-type
    - admin
  security:
    - cookie-auth: []
    - admin-role: []
  requestBody:
    description: New order payment type.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            orderPaymentTypeName:
              type: string
  responses:
    201:
      description: Created new order payment type.
      content:
        application/json:
          example:
            id: 1
            name: Visa
            createDate: 00.11.2222
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    409:
      $ref: './responses/409.yaml'

get:
  tags:
    - order-payment-type
    - admin
  summary: Get all order payment types.
  security:
    - cookie-auth: []
    - admin-role: []
  parameters:
    - $ref: './parameters/pagination/page-from.yaml'
    - $ref: './parameters/pagination/page-to.yaml'
  responses:
    200:
      description: All order payments received.
      content:
        application/json:
          schema:
            type: array
            items:
              $ref: './schemas/order-payment-type.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    404:
      $ref: './responses/404.yaml'
