post:
  summary: Create a new order payment type.
  tags:
    - order-payment-type
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  parameters:
    - name: order-payment-type-name
      in: query
      description: Order payment type name.
      schema:
        type: string
  responses:
    201:
      description: Created new order payment type.
      content:
        application/json:
          example:
            id: 1
            name: Visa
            createDate: 00.11.2222
    400:
      $ref: './responses/validation/400.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    409:
      $ref: '../../responses/order-payment-type/order-payment-type-with-this-name-already-exists.yaml'

get:
  tags:
    - order-payment-type
  summary: Get all order payment types.
  security:
    - cookie-auth: [ ]
    - admin-role: [ ]
  responses:
    200:
      description: All order payments received.
      content:
        application/json:
          schema:
            $ref: './schemas/order-payment-type/order-payment-types.yaml'
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    404:
      description: No categories found.