post:
  summary: Create new feedback.
  tags:
    - feedback
  security:
    - cookie-auth: [ ]
    - customer-role: [ ]
  requestBody:
    description: Feedback data for creating new feedback.
    required: true
    content:
      application/json:
        schema:
          type: object
          properties:
            userId:
              type: integer
            productId:
              type: integer
            companyId:
              type: integer
            rating:
              type: integer
              minimum: 1
              maximum: 5
              default: 5
            title:
              type: string
              minLength: 15
            message:
              type: string
              minLength: 50
  responses:
    201:
      description: Created new user feedback.
      content:
        application/json:
          schema:
            $ref: './schemas/feedback.yaml'
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'