type: object
properties:
  companyId:
    type: integer
  categoryId:
    type: integer
  quantity:
    type: integer
    default: 0
  price:
    type: integer
  rating:
    type: integer
    default: 5
  linkToImages:
    type: string
  title:
    type: string
  description:
    type: string
    minLength: 50
example:
  id: 1
  companyId: 1
  categoryId: 1
  quantity: 17
  price: 3500
  rating: 4
  linkToImages: linkToImages
  title: concrete
  description: concrete
  createDate: 00.11.2222
  updateDate: 99.88.7777