openapi: 3.0.0

info:
  title: builder-materials-market
  description: Online store for purchasing various building materials from various companies.yaml.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1/
    description: Main application server.

tags:
  - name: user-role
    description: Manage user roles for administrator.
  - name: user-status
    description: Manage user status for administrator.
  - name: user
    description: Custom data management and administrative panel.
  - name: order-status
    description: Manage order statues for administrator.
  - name: category
    description: Manage category for administrator and viewing for user.
  - name: company
    description: All information about the company and data management by the administrator.
  - name: product
    description: All information about products of different companies and administration.
  - name: feedback
    description: Product reviews.
  - name: order-payment-type
    description: Manage order payment type for administrator.
  - name: order
    description: Order management
  - name: order-detail
    description: Management of each item of a specific order.
  - name: order-history
    description: View and manage your order history.
  - name: delivery
    description: Custom Delivery Management.
  - name: auth-audit-event
    description: Manage audit event for administrator.

components:
  securitySchemes:
    cookie-auth:
      $ref: './security/cookie-auth.yaml'
    admin-role:
      $ref: './security/admin-role.yaml'
    customer-role:
      $ref: './security/customer-role.yaml'
  responses:
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    400:
      $ref: './responses/validation/400.yaml'
  schemas:
    user-role:
      $ref: './schemas/user-role/user-role.yaml'
    user-roles:
      $ref: './schemas/user-role/user-roles.yaml'
    user-status:
      $ref: './schemas/user-status/user-status.yaml'
    user-statuses:
      $ref: './schemas/user-status/user-statuses.yaml'
    user:
      $ref: './schemas/user/user.yaml'
    users:
      $ref: './schemas/user/users.yaml'
    order-status:
      $ref: './schemas/order-status/order-status.yaml'
    order-statuses:
      $ref: './schemas/order-status/order-statuses.yaml'
    category:
      $ref: './schemas/category/category.yaml'
    categories:
      $ref: './schemas/category/categories.yaml'
    company:
      $ref: './schemas/company/company.yaml'
    companies:
      $ref: './schemas/company/companies.yaml'
    product:
      $ref: './schemas/product/product.yaml'
    products:
      $ref: './schemas/product/products.yaml'
    feedback:
      $ref: './schemas/feedback/feedback.yaml'
    feedbacks:
      $ref: './schemas/feedback/feedbacks.yaml'
    order-payment-type:
      $ref: './schemas/order-payment-type/order-payment-type.yaml'
    order-payment-types:
      $ref: './schemas/order-payment-type/order-payment-types.yaml'
    order:
      $ref: './schemas/order/order.yaml'
    orders:
      $ref: './schemas/order/orders.yaml'
    order-detail:
      $ref: './schemas/order-detail/order-detail.yaml'
    order-details:
      $ref: './schemas/order-detail/order-details.yaml'
    order-history:
      $ref: './schemas/order-history/order-history.yaml'
    order-histories:
      $ref: './schemas/order-history/order-histories.yaml'
    delivery:
      $ref: './schemas/delivery/delivery.yaml'
    deliveries:
      $ref: './schemas/delivery/deliveries.yaml'
    session:
      $ref: './schemas/session/session.yaml'
    sessions:
      $ref: './schemas/session/sessions.yaml'
    auth-audit-event:
      $ref: './schemas/auth-audit-event/auth-audit-event.yaml'
    auth-audit-events:
      $ref: './schemas/auth-audit-event/auth-audit-events.yaml'
  parameters:
    user-role-id:
      $ref: './parameters/user-role/user-role-id.yaml'
    user-status-id:
      $ref: './parameters/user-status/user-status-id.yaml'
    user-id:
      $ref: './parameters/user/user-id.yaml'
    query-user-id:
      $ref: './parameters/user/query-user-id.yaml'
    order-status-id:
      $ref: './parameters/order-status/order-status-id.yaml'
    query-order-status-id:
      $ref: './parameters/order-status/query-order-status-id.yaml'
    category-id:
      $ref: './parameters/category/category-id.yaml'
    query-category-id:
      $ref: './parameters/category/query-category-id.yaml'
    company-id:
      $ref: './parameters/company/company-id.yaml'
    company-name:
      $ref: './parameters/company/company-name.yaml'
    query-company-id:
      $ref: './parameters/company/query-company-id.yaml'
    product-id:
      $ref: './parameters/product/product-id.yaml'
    product-name:
      $ref: './parameters/product/product-title.yaml'
    query-product-id:
      $ref: './parameters/product/query-product-id.yaml'
    feedback-id:
      $ref: './parameters/feedback/feedback-id.yaml'
    order-payment-type-id:
      $ref: './parameters/order-payment-type/order-payment-type-id.yaml'
    query-order-payment-type-id:
      $ref: './parameters/order-payment-type/query-order-payment-type-id.yaml'
    order-id:
      $ref: './parameters/order/order-id.yaml'
    query-order-id:
      $ref: './parameters/order/query-order-id.yaml'
    delivery-id:
      $ref: './parameters/delivery/delivery-id.yaml'
    session-id:
      $ref: './parameters/session/session-id.yaml'
    auth-audit-event-id:
      $ref: './parameters/auth-audit-event/auth-audit-event-id.yaml'

paths:
  /user-role:
    $ref: './paths/user-role/base.yaml'
  /user-role/{user-role-id}:
    $ref: './paths/user-role/{user-role-id}.yaml'
  /user-status:
    $ref: './paths/user-status/base.yaml'
  /user-status/{user-status-id}:
    $ref: './paths/user-status/{user-status-id}.yaml'
  /user:
    $ref: './paths/user/base.yaml'
  /user/{user-id}:
    $ref: './paths/user/{user-id}.yaml'
  /user/blocked/{user-id}:
    $ref: './paths/user/blocked/{user-id}.yaml'
  /user/unblocked/{user-id}:
    $ref: './paths/user/unblocked/{user-id}.yaml'
  /user/deleted/{user-id}:
    $ref: './paths/user/deleted/{user-id}.yaml'
  /user/undeleted/{user-id}:
    $ref: './paths/user/undeleted/{user-id}.yaml'
  /order-status:
    $ref: './paths/order-status/base.yaml'
  /order-status/{order-status-id}:
    $ref: './paths/order-status/{order-status-id}.yaml'
  /category:
    $ref: './paths/category/base.yaml'
  /category/{category-id}:
    $ref: './paths/category/{category-id}.yaml'
  /company:
    $ref: './paths/company/base.yaml'
  /company/{company-id}:
    $ref: './paths/company/{company-id}.yaml'
  /company/{company-name}:
    $ref: './paths/company/{company-name}.yaml'
  /product:
    $ref: './paths/product/base.yaml'
  /product/{product-id}:
    $ref: './paths/product/{product-id}.yaml'
  /product/{product-title}:
    $ref: './paths/product/{product-title}.yaml'
  /product/sort-by/category/{category-id}:
    $ref: './paths/product/sort-by/category/{category-id}.yaml'
  /product/sort-by/company/{company-id}:
    $ref: './paths/product/sort-by/company/{company-id}.yaml'
  /product/sort-by/category-and-company:
    $ref: './paths/product/sort-by/category-and-company/base.yaml'
  /product/sort-by/price:
    $ref: './paths/product/sort-by/price/base.yaml'
  /feedback:
    $ref: './paths/feedback/base.yaml'
  /feedback/{feedback-id}:
    $ref: './paths/feedback/{feedback-id}.yaml'
  /feedback/sort-by/user/{user-id}:
    $ref: './paths/feedback/sort-by/user/{user-id}.yaml'
  /feedback/sort-by/product/{product-id}:
    $ref: './paths/feedback/sort-by/product/{product-id}.yaml'
  /feedback/sort-by/rating/:
    $ref: './paths/feedback/sort-by/rating/base.yaml'
  /order-payment-type:
    $ref: './paths/order-payment-type/base.yaml'
  /order-payment-type/{order-payment-type-id}:
    $ref: './paths/order-payment-type/{order-payment-type-id}.yaml'
  /order:
    $ref: './paths/order/base.yaml'
  /order/{order-id}:
    $ref: './paths/order/{order-id}.yaml'
  /order/cancel/{order-id}:
    $ref: './paths/order/cancel/{order-id}.yaml'
  /order/set-payment-type/{order-id}:
    $ref: './paths/order/set-payment-type/{order-id}.yaml'
  /order/payment/{order-id}:
    $ref: './paths/order/payment/{order-id}.yaml'
  /order/sort-by/user/{user-id}:
    $ref: './paths/order/sort-by/user/{user-id}.yaml'
  /order/sort-by/user/status/{status-id}:
    $ref: './paths/order/sort-by/user/status/{status-id}.yaml'
  /order-detail:
    $ref: './paths/order-detail/base.yaml'
  /order-history:
    $ref: './paths/order-history/base.yaml'
  /delivery:
    $ref: './paths/delivery/base.yaml'
  /delivery/{delivery-id}:
    $ref: './paths/delivery/{delivery-id}.yaml'
  /session:
    $ref: './paths/session/base.yaml'
  /session/{session-id}:
    $ref: './paths/session/{session-id}.yaml'
  /auth-audit-event:
    $ref: './paths/auth-audit-event/base.yaml'
  /auth-audit-event/{auth-audit-event-id}:
    $ref: './paths/auth-audit-event/{auth-audit-event-id}.yaml'