openapi: 3.0.0

info:
  title: builder-materials-market
  description: Online store for purchasing various building materials from various companies.
  version: 1.0.0

servers:
  - url: http://localhost:8080
    description: Main application server.

tags:
  - name: User-Role
    description: Manage user roles for administrator.

components:
  securitySchemes:
    CookieAuth:
      $ref: './security/CookieAuth.yaml'
    AdminAuth:
      $ref: './security/AdminRole.yaml'
  responses:
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
  schemas:
    UserRole:
      $ref: './schemas/UserRole.yaml'
    UserRoles:
      $ref: './schemas/UserRoles.yaml'
  parameters:
    UserRoleId:
      $ref: './parameters/userRoleId.yaml'


paths:
  /user-role:
    $ref: './paths/user-role/base.yaml'
  /user-role/{user-role-id}:
    $ref: './paths/user-role/{user-role-id}.yaml'
