openapi: 3.0.0

info:
  title: builder-materials-market
  description: Online store for purchasing various building materials from various companies.yaml.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1/
    description: Main application server.

tags:
  - name: user-role
    description: Manage user roles for administrator.
  - name: user-status
    description: Manage user status for administrator.
  - name: user
    description: Custom data management and administrative panel.
  - name: order-status
    description: Manage order statues for administrator.
  - name: category
    description: Manage category for administrator and viewing for user.
  - name: company
    description: All information about the company and data management by the administrator.
  - name: product
    description: All information about products of different companies and administration.
  - name: feedback
    description: Product reviews.
  - name: order-payment-type
    description: Manage order payment type for administrator.
  - name: order
    description: Order management
  - name: order-detail
    description: Management of each item of a specific order.
  - name: order-history
    description: View and manage your order history.
  - name: delivery
    description: Custom Delivery Management.
  - name: auth-audit-event
    description: Manage audit event for administrator.

components:
  securitySchemes:
    cookie-auth:
      $ref: './security/cookie-auth.yaml'
    admin-role:
      $ref: './security/admin-role.yaml'
    customer-role:
      $ref: './security/customer-role.yaml'
  responses:
    400:
      $ref: './responses/400.yaml'
    401:
      $ref: './responses/401.yaml'
    403:
      $ref: './responses/403.yaml'
    404:
      $ref: './responses/404.yaml'
    409:
      $ref: './responses/409.yaml'


  schemas:
    user-role:
      $ref: './schemas/user-role.yaml'
    user-status:
      $ref: './schemas/user-status.yaml'
    user:
      $ref: './schemas/user.yaml'
    order-status:
      $ref: './schemas/order-status.yaml'
    category:
      $ref: './schemas/category.yaml'
    company:
      $ref: './schemas/company.yaml'
    product:
      $ref: './schemas/product.yaml'
    feedback:
      $ref: './schemas/feedback.yaml'
    order-payment-type:
      $ref: './schemas/order-payment-type.yaml'
    order:
      $ref: './schemas/order.yaml'
    order-detail:
      $ref: './schemas/order-detail.yaml'
    order-history:
      $ref: './schemas/order-history.yaml'
    delivery:
      $ref: './schemas/delivery.yaml'
    session:
      $ref: './schemas/session.yaml'
    auth-audit-event:
      $ref: './schemas/auth-audit-event.yaml'
    auth-audit:
      $ref: './schemas/auth-audit.yaml'
  parameters:
    user-role-id:
      $ref: './parameters/user-role/user-role-id.yaml'
    user-status-id:
      $ref: './parameters/user-status/user-status-id.yaml'
    user-id:
      $ref: './parameters/user/user-id.yaml'
    query-user-id:
      $ref: './parameters/user/query-user-id.yaml'
    order-status-id:
      $ref: './parameters/order-status/order-status-id.yaml'
    query-order-status-id:
      $ref: './parameters/order-status/query-order-status-id.yaml'
    category-id:
      $ref: './parameters/category/category-id.yaml'
    query-category-id:
      $ref: './parameters/category/query-category-id.yaml'
    company-id:
      $ref: './parameters/company/company-id.yaml'
    company-name:
      $ref: './parameters/company/company-name.yaml'
    query-company-id:
      $ref: './parameters/company/query-company-id.yaml'
    product-id:
      $ref: './parameters/product/product-id.yaml'
    product-name:
      $ref: './parameters/product/product-title.yaml'
    query-product-id:
      $ref: './parameters/product/query-product-id.yaml'
    feedback-id:
      $ref: './parameters/feedback/feedback-id.yaml'
    order-payment-type-id:
      $ref: './parameters/order-payment-type/order-payment-type-id.yaml'
    query-order-payment-type-id:
      $ref: './parameters/order-payment-type/query-order-payment-type-id.yaml'
    order-id:
      $ref: './parameters/order/order-id.yaml'
    query-order-id:
      $ref: './parameters/order/query-order-id.yaml'
    delivery-id:
      $ref: './parameters/delivery/delivery-id.yaml'
    session-id:
      $ref: './parameters/session/session-id.yaml'
    query-session-id:
      $ref: './parameters/session/query-session-id.yaml'
    auth-audit-event-id:
      $ref: './parameters/auth-audit-event/auth-audit-event-id.yaml'
    auth-audit-event:
      $ref: './parameters/auth-audit/auth-audit-id.yaml'

paths:
  # USER-ROLE
  /user-role:
    $ref: './paths/user-role/base.yaml'
  /user-role/{user-role-id}:
    $ref: './paths/user-role/{user-role-id}.yaml'

  # USER-STATUS
  /user-status:
    $ref: './paths/user-status/base.yaml'
  /user-status/{user-status-id}:
    $ref: './paths/user-status/{user-status-id}.yaml'

  # USER
  /user:
    $ref: './paths/user/base.yaml'
  /user/{user-id}:
    $ref: './paths/user/{user-id}.yaml'
  /user/{user-id}/blocked:
    $ref: './paths/user/blocked/{user-id}.yaml'
  /user/{user-id}/unblocked:
    $ref: './paths/user/unblocked/{user-id}.yaml'
  /user/{user-id}/deleted:
    $ref: './paths/user/deleted/{user-id}.yaml'
  /user/{user-id}/undeleted:
    $ref: './paths/user/undeleted/{user-id}.yaml'


  # ORDER-STATUS
  /order-status:
    $ref: './paths/order-status/base.yaml'
  /order-status/{order-status-id}:
    $ref: './paths/order-status/{order-status-id}.yaml'

  # CATEGORY
  /category:
    $ref: './paths/category/base.yaml'
  /category/{category-id}:
    $ref: './paths/category/{category-id}.yaml'

  # COMPANY
  /company:
    $ref: './paths/company/base.yaml'
  /company/{company-id}:
    $ref: './paths/company/{company-id}.yaml'
  /company/{company-name}:
    $ref: './paths/company/{company-name}.yaml'

  # PRODUCT
  /product:
    $ref: './paths/product/base.yaml'
  /product/{product-id}:
    $ref: './paths/product/{product-id}.yaml'
  /product/{product-title}:
    $ref: './paths/product/{product-title}.yaml'
  /product/category/{category-id}:
    $ref: './paths/product/category/{category-id}.yaml'
  /product/company/{company-id}:
    $ref: './paths/product/company/{company-id}.yaml'
  /product/company/{company-id}/category/{category-id}:
    $ref: './paths/product/company/category/{category-id}.yaml'
  /product/price:
    $ref: './paths/product/price/base.yaml'

  # FEEDBACK
  /feedback:
    $ref: './paths/feedback/base.yaml'
  /feedback/{feedback-id}:
    $ref: './paths/feedback/{feedback-id}.yaml'
  /feedback/user/{user-id}:
    $ref: './paths/feedback/user/{user-id}.yaml'
  /feedback/product/{product-id}:
    $ref: './paths/feedback/product/{product-id}.yaml'
  /feedback/rating/:
    $ref: './paths/feedback/rating/base.yaml'

  # ORDER-PAYMENT-TYPE
  /order-payment-type:
    $ref: './paths/order-payment-type/base.yaml'
  /order-payment-type/{order-payment-type-id}:
    $ref: './paths/order-payment-type/{order-payment-type-id}.yaml'

  # ORDER
  /order:
    $ref: './paths/order/base.yaml'
  /order/{order-id}:
    $ref: './paths/order/{order-id}.yaml'
  /order/{order-id}/cancel:
    $ref: './paths/order/cancel/{order-id}.yaml'
  /order/{order-id}/set-payment-type:
    $ref: './paths/order/set-payment-type/{order-id}.yaml'
  /order/{order-id}/payment:
    $ref: './paths/order/payment/{order-id}.yaml'
  /order/user/{user-id}:
    $ref: './paths/order/user/{user-id}.yaml'
  /order/user/{user-id  }/status/{status-id}:
    $ref: './paths/order/user/status/{status-id}.yaml'

  # ORDER-DETAIL
  /order-detail:
    $ref: './paths/order-detail/base.yaml'
  /order-detail/order/{order-id}:
    $ref: './paths/order-detail/order/{order-id}.yaml'
  /order-detail/order/{order-id}/product/{prodct-id}/:
    $ref: './paths/order-detail/order/product/{product-id}.yaml'

  # ORDER-HISTORY
  /order-history:
    $ref: './paths/order-history/base.yaml'
  /order-history/order/{order-id}:
    $ref: './paths/order-history/order/{order-id}.yaml'

  # DELIVERY
  /delivery:
    $ref: './paths/delivery/base.yaml'
  /delivery/{delivery-id}:
    $ref: './paths/delivery/{delivery-id}.yaml'

  # SESSION
  /session/{session-id}:
    $ref: './paths/session/{session-id}.yaml'
  /session/user/{user-id}:
    $ref: './paths/session/user/{user-id}.yaml'

  # AUTH-AUDIT-EVENT
  /auth-audit-event:
    $ref: './paths/auth-audit-event/base.yaml'
  /auth-audit-event/{auth-audit-event-id}:
    $ref: './paths/auth-audit-event/{auth-audit-event-id}.yaml'

  # AUTH-AUDIT
  /auth-audit/{auth-audit-id}:
    $ref: './paths/auth-audit/{auth-audit-id}.yaml'
  /auth-audit/user/{user-id}:
    $ref: './paths/auth-audit/user/{user-id}.yaml'
  /auth-audit/user/{user-id}/session/{session-id}:
    $ref: './paths/auth-audit/user/session/{session-id}.yaml'