openapi: 3.0.0

info:
  title: builder-materials-market
  description: Online store for purchasing various building materials from various companies.yaml.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1/
    description: Main application server.

tags:
  - name: no-auth
    description: Methods available without authorization.
  - name: admin
    description: methods for administrator
  - name: customer
    description: methods for customer
  - name: user-role
    description: Manage user roles for administrator.
  - name: user-status
    description: Manage user status for administrator.
  - name: user
    description: Custom data management and administrative panel.
  - name: order-status
    description: Manage order statues for administrator.
  - name: category
    description: Manage category for administrator and viewing for user.
  - name: company
    description: All information about the company and data management by the administrator.
  - name: product
    description: All information about products of different companies and administration.
  - name: order-payment-type
    description: Manage order payment type for administrator.
  - name: auth-audit-event
    description: Manage audit event for administrator.
  - name: auth
    description: Login management methods.
  - name: order
    description: User order management methods.
  - name: feedback
    description: User feedback management methods.
  - name: order-detail
    description: User order detail management methods.
  - name: session
    description: User session management methods.
  - name: delivery
    description: User order delivery management methods.

components:
  securitySchemes:
    cookie-auth:
      $ref: "./security/cookie-auth.yaml"
    admin-role:
      $ref: "./security/admin-role.yaml"
    customer-role:
      $ref: "./security/customer-role.yaml"
  responses:
    400:
      $ref: "./responses/400.yaml"
    401:
      $ref: "./responses/401.yaml"
    403:
      $ref: "./responses/403.yaml"
    404:
      $ref: "./responses/404.yaml"
    409:
      $ref: "./responses/409.yaml"
  schemas:
    user-role:
      $ref: "./schemas/user-role.yaml"
    user-status:
      $ref: "./schemas/user-status.yaml"
    user:
      $ref: "./schemas/user.yaml"
    order-status:
      $ref: "./schemas/order-status.yaml"
    category:
      $ref: "./schemas/category.yaml"
    company:
      $ref: "./schemas/company.yaml"
    product:
      $ref: "./schemas/product.yaml"
    feedback:
      $ref: "./schemas/feedback.yaml"
    order-payment-type:
      $ref: "./schemas/order-payment-type.yaml"
    order:
      $ref: "./schemas/order.yaml"
    order-detail:
      $ref: "./schemas/order-detail.yaml"
    order-history:
      $ref: "./schemas/order-history.yaml"
    delivery:
      $ref: "./schemas/delivery.yaml"
    session:
      $ref: "./schemas/session.yaml"
    auth-audit-event:
      $ref: "./schemas/auth-audit-event.yaml"
    auth-audit:
      $ref: "./schemas/auth-audit.yaml"
  parameters:
    page-from:
      $ref: "./parameters/pagination/page-from.yaml"
    page-to:
      $ref: "./parameters/pagination/page-to.yaml"
    userRoleId:
      $ref: "./parameters/user-role/userRoleId.yaml"
    userStatusId:
      $ref: "./parameters/user-status/userStatusId.yaml"
    userId:
      $ref: "./parameters/user/userId.yaml"
    queryUserId:
      $ref: "./parameters/user/queryUerId.yaml"
    orderStatusId:
      $ref: "./parameters/order-status/orderStatusId.yaml"
    queryOrderStatusId:
      $ref: "./parameters/order-status/queryOrderStatusId.yaml"
    categoryId:
      $ref: "./parameters/category/categoryId.yaml"
    queryCategoryId:
      $ref: "./parameters/category/queryCategoryId.yaml"
    companyId:
      $ref: "./parameters/company/companyId.yaml"
    query-companyId:
      $ref: "./parameters/company/queryCompanyId.yaml"
    productId:
      $ref: "./parameters/product/productId.yaml"
    queryProductId:
      $ref: "./parameters/product/queryProductId.yaml"
    feedbackId:
      $ref: "./parameters/feedback/feedbackId.yaml"
    orderPaymentTypeId:
      $ref: "./parameters/order-payment-type/orderPaymentTypeId.yaml"
    queryOrderPaymentTypeId:
      $ref: "./parameters/order-payment-type/queryOrderPaymentTypeId.yaml"
    orderId:
      $ref: "./parameters/order/orderId.yaml"
    queryOrderId:
      $ref: "./parameters/order/queryOrderId.yaml"
    sessionId:
      $ref: "./parameters/session/sessionId.yaml"
    querySessionId:
      $ref: "./parameters/session/querySessionId.yaml"
    authAuditEventId:
      $ref: "./parameters/auth-audit-event/authAuditEventId.yaml"
    orderDetailId:
      $ref: "./parameters/order-detail/orderDetailId.yaml"

paths:
  # USER-ROLES
  /user-roles:
    $ref: "./paths/user-role/base.yaml"
  /user-roles/{userRoleId}:
    $ref: "./paths/user-role/{userRoleId}.yaml"

  # USER-STATUSES
  /user-statuses/:
    $ref: "./paths/user-status/base.yaml"
  /user-statuses/{userStatusId}:
    $ref: "./paths/user-status/{userStatusId}.yaml"

  # ORDER-STATUSES
  /order-statuses:
    $ref: "./paths/order-status/base.yaml"
  /order-statuses/{orderStatusId}:
    $ref: "./paths/order-status/{orderStatusId}.yaml"

  # ORDER-PAYMENT-TYPES
  /order-payment-types:
    $ref: "./paths/order-payment-type/base.yaml"
  /order-payment-types/{orderPaymentTypeId}:
    $ref: "./paths/order-payment-type/{orderPaymentTypeId}.yaml"

  # AUTH-AUDIT-EVENTS
  /auth-audit-events:
    $ref: "./paths/auth-audit-event/base.yaml"
  /auth-audit-events/{authAuditEventId}:
    $ref: "./paths/auth-audit-event/{authAuditEventId}.yaml"

  # AUTH
  /auth/log-in:
    $ref: "./paths/auth/log-in/base.yaml"
  /auth/log-out:
    $ref: "./paths/auth/log-out/base.yaml"

  # CATEGORIES
  /categories:
    $ref: "./paths/category/base.yaml"
  /categories/{categoryId}:
    $ref: "./paths/category/{categoryId}.yaml"

  # COMPANY
  /companies:
    $ref: "./paths/company/base.yaml"
  /companies/{companyId}:
    $ref: "./paths/company/{companyId}.yaml"

  # PRODUCTS
  /products:
    $ref: "./paths/product/base.yaml"
  /products/{productId}:
    $ref: "./paths/product/{productId}.yaml"

  # USERS
  /users/:
    $ref: "./paths/user/base.yaml"
  /users/{userId}:
    $ref: "./paths/user/{userId}.yaml"

  # ORDERS
  /orders:
    $ref: "./paths/order/base.yaml"
  /orders/{orderId}:
    $ref: './paths/order/{orderId}.yaml'
  /orders/{orderId}/history:
    $ref: "./paths/order/history/base.yaml"

  # DELIVERY
  /delivery:
    $ref: "./paths/user/order/delivery/base.yaml"

  # ORDER-DETAILS
  /orders/{orderId}/order-details:
    $ref: "./paths/user/order/products/base.yaml"
  /orders/{orderId}/order-details/{orderDetailId}:
    $ref: "./paths/user/order/products/{productId}.yaml"

  # FEEDBACK
  /feedbacks:
    $ref: "./paths/user/feedback/base.yaml"
  /feedbacks/{feedbackId}:
    $ref: "./paths/user/feedback/{feedbackId}.yaml"

  # SESSIONS
  /sessions:
    $ref: "./paths/user/session/base.yaml"
  /sessions/{sessionId}:
    $ref: "./paths/user/session/{sessionId}.yaml"
  /sessions/{sessionId}/auth-audits:
    $ref: "./paths/user/session/auth-audit/base.yaml"
