openapi: 3.0.0

info:
  title: builder-materials-market
  description: Online store for purchasing various building materials from various companies.
  version: 1.0.0

servers:
  - url: http://localhost:8080/api/v1/
    description: Main application server.

tags:
  - name: user-role
    description: Manage user roles for administrator.
  - name: user-status
    description: Manage user status for administrator.
  - name: user
    description: Custom data management and administrative panel.
  - name: order-status
    description: Manage order statues for administrator.
  - name: category
    description: Manage category for administrator and viewing for user.

components:
  securitySchemes:
    cookie-auth:
      $ref: './security/cookie-auth.yaml'
    admin-role:
      $ref: './security/admin-role.yaml'
    customer-role:
      $ref: './security/customer-role.yaml'
  responses:
    401:
      $ref: './responses/auth/401.yaml'
    403:
      $ref: './responses/auth/403.yaml'
    400:
      $ref: './responses/validation/400.yaml'
  schemas:
    user-role:
      $ref: './schemas/user-role/user-role.yaml'
    user-roles:
      $ref: './schemas/user-role/user-roles.yaml'
    user-status:
      $ref: './schemas/user-status/user-status.yaml'
    user-statuses:
      $ref: './schemas/user-status/user-statuses.yaml'
    user:
      $ref: './schemas/user/user.yaml'
    users:
      $ref: './schemas/user/users.yaml'
    order-status:
      $ref: './schemas/order-status/order-status.yaml'
    order-statuses:
      $ref: './schemas/order-status/order-statuses.yaml'
    category:
      $ref: './schemas/category/category.yaml'
    categories:
      $ref: './schemas/category/categories.yaml'
  parameters:
    user-role-id:
      $ref: './parameters/user-role/user-role-id.yaml'
    user-status-id:
      $ref: './parameters/user-status/user-status-id.yaml'
    user-id:
      $ref: './parameters/user/user-id.yaml'
    order-status-id:
      $ref: './parameters/order-status/order-status-id.yaml'
    category-id:
      $ref: './parameters/category/category.yaml'

paths:
  /user-role:
    $ref: './paths/user-role/base.yaml'
  /user-role/{user-role-id}:
    $ref: './paths/user-role/{user-role-id}.yaml'
  /user-status:
    $ref: './paths/user-status/base.yaml'
  /user-status/{user-status-id}:
    $ref: './paths/user-status/{user-status-id}.yaml'
  /user:
    $ref: './paths/user/base.yaml'
  /user/{user-id}:
    $ref: './paths/user/{user-id}.yaml'
  /user/blocked/{user-id}:
    $ref: './paths/user/blocked/{user-id}.yaml'
  /user/unblocked/{user-id}:
    $ref: './paths/user/unblocked/{user-id}.yaml'
  /user/deleted/{user-id}:
    $ref: './paths/user/deleted/{user-id}.yaml'
  /user/undeleted/{user-id}:
    $ref: './paths/user/undeleted/{user-id}.yaml'
  /order-status:
    $ref: './paths/order-status/base.yaml'
  /order-status/{order-status-id}:
    $ref: './paths/order-status/{order-status-id}.yaml'
  /category:
    $ref: './paths/category/base.yaml'
  /category/{category-id}:
    $ref: './paths/category/{category-id}.yaml'