openapi: 3.0.0
info:
  title: builder-materials-market
  description: Online store for purchasing various building materials from various
    companies.
  version: 1.0.0
servers:
  - url: http://localhost:8080
    description: Main application server.
tags:
  - name: User-Role
    description: Manage user roles for administrator.
components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: Authorization
      description: User session token.
    AdminAuth:
      type: apiKey
      in: cookie
      name: Admin
      description: Role for administrator.
  responses:
    "401":
      description: User is not authenticate.
    "403":
      description: User is not administrator.
  schemas:
    UserRole:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        createDate:
          type: string
        updateDate:
          type: string
      example:
        id: 1
        name: Harry Potter
        createDate: 00.11.2222
        updateDate: 99.88.7777
    UserRoles:
      type: array
      items:
        $ref: "#/components/schemas/UserRole"
paths:
  /user-role:
    post:
      summary: Create a new user role.
      tags:
        - User-Role
      security:
        - CookieAuth: []
        - AdminRole: []
      requestBody:
        description: User role name.
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
      responses:
        "201":
          description: Created new user role.
          content:
            application/json:
              example:
                id: 1
                name: admin
                createDate: 00.00.0000
        "400":
          description: User role with this name already exists.
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
    get:
      tags:
        - User-Role
      summary: Get all user roles.
      security:
        - CookieAuth: []
        - AdminRole: []
      responses:
        "200":
          description: All user role received.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/UserRoles"
        "401":
          $ref: "#/components/responses/401"
        "403":
          $ref: "#/components/responses/403"
        "404":
          description: No user role found.
